name: vagrant-build

on: [push]

jobs:
  build:
    runs-on: macos-10.15
    timeout-minutes: 720

    steps:
    - uses: actions/checkout@v2

    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Run vagrant up
      run: vagrant up

    - name: Run scripts
      run: vagrant ssh -c 'cd lfs && sudo sh scripts/run-all.sh'

    - name: Copy ISO from vagrant
      run: vagrant ssh -c 'cat /tmp/lfs.iso' > ~/lfs.iso

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: LFS iso image from Vagrant build
        path: ~/lfs.iso
        retention-days: 5
